version: '3.8'

services:
  client:
    build: visweshdocker/pmcclientside
    ports:
      - "5173:5173"
    env_file:
      - .env

  server:
    build: visweshdocker/pmcserverside
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 8G
    env_file:
      - .env
    restart: always

  prometheus:
    image: prom/prometheus:v2.20.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.1.5
    ports:
      - "8080:3000"
    env_file:
      - .env
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
